services:
  insight_places_cases:
    build:
      context: configs
    container_name: insight_places_cases
    volumes:
      - './app:/app'
    working_dir: '/app'
  insight_places_case_db:
    image: 'mysql:latest'
    container_name: insight_places_case_db
    environment:
      - MYSQL_ROOT_PASSWORD=strongpassword
    ports:
      - '7612:3306'

